export const refs = {
    header: document.querySelector('#header'),
    mobMenuBtn: document.querySelector('#burger'),
    mobMenu: document.querySelector('#mobile-menu'),
    searchForm: document.querySelector('#search'),
    input: document.querySelector('#search__input'),
    searchOpen: document.querySelector('#search__open'),
    searchClose: document.querySelector('#search__close'),
    slider: document.querySelector('.hero__slider'),
    prev: document.querySelector('.hero__btn--prev'),
    next: document.querySelector('.hero__btn--next'),
    gallery: document.querySelector('.projects__list'),
    loadMoreBtn: document.querySelector('.projects__btn'),
    gradient: document.querySelector('.projects__gradient'),
};